# Generated by Django 5.1.6 on 2025-03-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
    ]
