# Generated by Django 5.1.7 on 2025-03-10 23:53

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=functools.partial(core.models.model_image_file_path, *(), **{'model': 'product'})),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=functools.partial(core.models.model_image_file_path, *(), **{'model': 'user'})),
        ),
    ]
