# Generated by Django 5.1.6 on 2025-03-06 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to=models.Q(('is_staff', False), models.Q(('doctor__isnull', False), _negated=True)), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
