# Generated by Django 5.1.7 on 2025-03-12 03:05

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(core.models.model_image_file_path, *(), **{'model': 'user'})),
        ),
    ]
