# Generated by Django 5.1.6 on 2025-02-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.hospital'),
        ),
    ]
