# Generated by Django 5.1.6 on 2025-02-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_event_doctor_alter_event_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='practice_number',
            field=models.IntegerField(unique=True),
        ),
    ]
