# Generated by Django 5.1.6 on 2025-02-13 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
