# Generated by Django 5.1.6 on 2025-02-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_user_hospital_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hospital',
        ),
    ]
