# Generated by Django 5.1.6 on 2025-02-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='name',
            new_name='patient_name',
        ),
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(default='default procedure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient_age',
            field=models.PositiveSmallIntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient_number',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient_surname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedure',
            name='ward',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
