# Generated by Django 5.1.6 on 2025-02-14 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_name_procedure_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procedure', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procedure',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moified_procedures', to=settings.AUTH_USER_MODEL),
        ),
    ]
