# Generated by Django 5.1.6 on 2025-02-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_procedure_created_by_procedure_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='patient_number',
        ),
        migrations.AddField(
            model_name='procedure',
            name='case_number',
            field=models.CharField(max_length=64, unique=True, blank=True, null=True),
            preserve_default=False,
        ),
    ]
