# Generated by Django 5.1.6 on 2025-02-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_procedure_patient_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cataloge_id', models.IntegerField()),
                ('profile', models.DecimalField(decimal_places=1, max_digits=1)),
                ('type', models.TextField(choices=[('Plate', [('Titanium Mesh', 'Titanium Mesh')]), ('Instruments', [('Scissors', 'Scissors'), ('Drill', 'Drill'), ('Screwdriver', 'Screwdriver'), ('Screwdriver Holding Device', 'Screwdriver Holding Device')]), ('Screw', 'Screw'), ('Rack', 'Rack'), ('Containers', [('Container', 'Container'), ('Rack', 'Rack'), ('Tray', 'Tray')])])),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='case_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
