# Generated by Django 5.1.6 on 2025-02-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_item_alter_procedure_case_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='item_type',
        ),
    ]
