# Generated by Django 5.1.6 on 2025-02-18 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_type_item_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cataloge_id',
            new_name='catalogue_id',
        ),
    ]
