# Generated by Django 5.1.6 on 2025-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_cataloge_id_item_catalogue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='profile',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
