# Generated by Django 5.1.6 on 2025-02-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='case_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
