# Generated by Django 5.1.6 on 2025-02-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_procedure_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='case_number',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
