# Generated by Django 5.1.6 on 2025-02-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_procedure_case_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogue_id', models.IntegerField()),
                ('profile', models.DecimalField(decimal_places=1, max_digits=4)),
                ('item_type', models.TextField(choices=[('Plates', [('Plate', 'Plate'), ('Titanium Mesh', 'Titanium Mesh')]), ('Instruments', [('Scissors', 'Scissors'), ('Drill', 'Drill'), ('Screwdriver', 'Screwdriver'), ('Screwdriver Holding Device', 'Screwdriver Holding Device')]), ('Containers', [('Container', 'Container'), ('Rack', 'Rack'), ('Tray', 'Tray')]), ('Other', [('Screw', 'Screw')])])),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vat_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='item',
        ),
        migrations.AddField(
            model_name='allocation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.equipment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
