# Generated by Django 5.1.6 on 2025-02-18 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_equipment_remove_allocation_item_allocation_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'equipment'},
        ),
    ]
