# Generated by Django 5.1.6 on 2025-02-19 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allocation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moified_allocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
